version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Ensure DB is ready before Django starts
    environment:
      - DEBUG=True
      - DB_NAME=vetmanager_db
      - DB_USER=vetmanager_user
      - DB_PASSWORD=vetmanager_password
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - vetmanager_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vetmanager_db
      POSTGRES_USER: vetmanager_user
      POSTGRES_PASSWORD: vetmanager_password
    ports:
      - "5432:5432"
    networks:
      - vetmanager_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vetmanager_user -d vetmanager_db"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  vetmanager_network:
