version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_NAME=vetmanager_db
      - DB_USER=vetmanager_user
      - DB_PASSWORD=vetmanager_password
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vetmanager_db
      POSTGRES_USER: vetmanager_user
      POSTGRES_PASSWORD: vetmanager_password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
