# Generated by Django 5.1.11 on 2025-06-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='veterinarian',
            table='veterinarian',
        ),
    ]
