# Generated by Django 5.1.11 on 2025-06-15 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
        ('veterinarian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinarian.veterinarian')),
            ],
            options={
                'db_table': 'vet_subscription',
            },
        ),
    ]
