# Generated by Django 5.1.11 on 2025-06-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_subscription', '0002_initial'),
        ('veterinarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetsubscription',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinarian.veterinarian'),
        ),
    ]
