# Generated by Django 5.1.7 on 2025-03-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('castrated', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('has_microchip', models.BooleanField()),
                ('microchip_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'animal',
            },
        ),
    ]
