# Generated by Django 5.1.11 on 2025-06-15 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('castrated', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('has_microchip', models.BooleanField()),
                ('microchip_id', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='owner.owner')),
            ],
            options={
                'db_table': 'animal',
            },
        ),
    ]
