# Generated by Django 5.1.11 on 2025-06-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='number_of_animals',
            field=models.IntegerField(default=0),
        ),
    ]
