# Generated by Django 5.1.7 on 2025-03-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='owner',
            table='owner',
        ),
    ]
